language: python

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - graphviz

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphviz; fi

python:
- '3.8'
install: pip install .[dev]

script: python -m pytest
after_success: bash <(curl -s https://codecov.io/bash) -t 94150045-9c0d-4b51-8116-e1606ab7a72e
